from __future__ import annotations

from typing import Any, overload

float64: object

class NDArray:
    @overload
    def __getitem__(self, key: int) -> float: ...
    @overload
    def __getitem__(self, key: slice) -> NDArray: ...
    @overload
    def __getitem__(self, key: Any) -> float | NDArray: ...
    @overload
    def __setitem__(self, key: int, value: float) -> None: ...
    @overload
    def __setitem__(self, key: slice, value: list[float] | NDArray) -> None: ...
    @overload
    def __setitem__(self, key: Any, value: object) -> None: ...
    def tolist(self) -> list[float]: ...

def asarray(obj: object, *, dtype: object = ...) -> NDArray: ...
def empty(shape: int, *, dtype: object = ...) -> NDArray: ...
